name: wakeUpOnProject

# on:
#   schedule:
#     - cron: "*/14 * * * *" # Pinga a cada 14 minutos
#   workflow_dispatch:

jobs:
  keep-alive:
    name: Ping Render site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Ping site
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
        run: npm start
